In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1d python list and 1d numpy array
print([1,2,3,4,5])
print(type([1,2,3,4,5]))
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr.shape

# 2d python list and , 2d numpy array
print([[1,2,3],[4,5,6]])
print(type([[1,2,3],[4,5,6]]))
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [3]:
# creating pandas series using numpy 1d  array
s = pd.Series(arr)
print(s)
print(type(s))

# creating pandas DataFrame using numpy 2d array
s2 = pd.DataFrame(arr2)
print(s2)
print(type(s2))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
   0  1  2
0  1  2  3
1  4  5  6
<class 'pandas.core.frame.DataFrame'>


series with cutom index

In [4]:
# s = pd.Series(arr,index=["a","b","c","d","e"])
s = pd.Series([10,20,30,40,50],index=["a","b","c","d","e"])
print(s)
print(type(s))

a    10
b    20
c    30
d    40
e    50
dtype: int64
<class 'pandas.core.series.Series'>


In [5]:
# accessing series elements
print(s["a"])
print(s["e"])

10
50


DataFrame

In [6]:
data ={
    "name":["maruf","rifat","shifat"],
    "age":[110,1000,1000],
    "city":["Dhaka","Ranpur","Dinajpur"]
}
print(data)
print(type(data))

{'name': ['maruf', 'rifat', 'shifat'], 'age': [110, 1000, 1000], 'city': ['Dhaka', 'Ranpur', 'Dinajpur']}
<class 'dict'>


In [7]:
df = pd.DataFrame(data)
print(df)
print(type(df))

     name   age      city
0   maruf   110     Dhaka
1   rifat  1000    Ranpur
2  shifat  1000  Dinajpur
<class 'pandas.core.frame.DataFrame'>


In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
arr = np.array(df.columns)
print(type(df.columns))
print(df.columns)
print(type(arr))
print(arr)

<class 'pandas.core.indexes.base.Index'>
Index(['name', 'age', 'city'], dtype='object')
<class 'numpy.ndarray'>
['name' 'age' 'city']


AttributeError: 'Series' object has no attribute 'columns'