Vetorization

In [ ]:
# importing numpy
import numpy as np

In [5]:
# vectorization
arr = np.array([1,2,3,4,5])
print(arr)
result = arr ** 2 #vectorized operation
print("result array: ",result)

[1 2 3 4 5]
result array:  [ 1  4  9 16 25]


What is Broadcasting?

Broadcasting is NumPy’s way of handling operations between arrays of different shapes without making unnecessary copies.

The Rule of Broadcasting:

For two arrays to be compatible:

If dimensions match → ✅ works directly.

If one dimension is 1 → ✅ NumPy stretches it.

Otherwise → ❌ error.

In [ ]:
# Broadcasting
result = result + 10 # result is an array and 10 is an integer
result

array([11, 14, 19, 26, 35])

In [8]:
# Broadcasting in 2d array
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([1,2,3])
result = arr1+arr2
print(result)

[[2 4 6]
 [5 7 9]]


Normalization using Broadcasting

In [15]:
data = np.array([[10,20,30],
                [15,25,35],
                [20, 30,40],
                [25,35,45],
                [30,40,50]])
print(data)
print(data.shape)
mean = data.mean(axis=0) #mean
print("mean is: ",mean)
std = data.std(axis=0) #standard deviation
print(std)

[[10 20 30]
 [15 25 35]
 [20 30 40]
 [25 35 45]
 [30 40 50]]
(5, 3)
mean is:  [20. 30. 40.]
[7.07106781 7.07106781 7.07106781]


In [16]:
# normalizing the data
normalized_data = (data-mean)/std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
