In [15]:
import numpy as np

2D array and axis

In [16]:
arr = np.array([[1,2,3],
                [7,8,9]])
print(type(arr))
print(arr.shape)
print(arr)

print(arr[0]) #prints row 0
print(arr[1]) #prints row 1

# numpy native multidimensional indexing
# very fast
# has more functionality
print(arr[0,1]) #prints element of the 0th row and 1st column

#python-style chained indexing
# slightly slow
# has less functionality
print(arr[0][1])#prints element of the 0th row and 1st column


<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [7 8 9]]
[1 2 3]
[7 8 9]
2
2


In [17]:
# sum
print(np.sum(arr)) # gives sum of the complete array
print(np.sum(arr,axis=0)) #gives sum of the rows
print(np.sum(arr,axis=1)) #gives sum of the columns

arr = np.array([2,3])
print(arr.shape)
print(arr.ndim)
print(arr[0])

30
[ 8 10 12]
[ 6 24]
(2,)
1
2


In [18]:
# slicing the array
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("0th row: ",arr[0]) #prints 0th row ot the array
# or
# numpy style dimensioning
print("0th row: ",arr[0,:]) #prints 0th row of the array

print("0th: ",arr[0:3,0:1]) #prints 0th column of the array
print("1st: ",arr[:,1])#prints 1st column of the array
print("2nd: ",arr[:,2]) #prints 2nd column of the array

print("array is: \n",arr)
print("last 2 elements of the first row: ",arr[0,1:3])

# so the syntax is print(arr[startRow:takeRow+1, startCol:takeCol+1]) for 2d array

0th row:  [1 2 3]
0th row:  [1 2 3]
0th:  [[1]
 [4]
 [7]]
1st:  [2 5 8]
2nd:  [3 6 9]
array is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
last 2 elements of the first row:  [2 3]


3D array and axis

In [35]:
# 3d array is basically an array of 2d arrays
# 3d array has depth , rows , columns
# depth represents 2d arrays
# row represents rows of each 2d arrays
# column represents columns of each 2d arrays

arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
       [7,8,9],
       [10,11,12] 
    ]
])
print(arr3d)
print("shape of the array: ",arr3d.shape)
print("dimension of the array:",arr3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape of the array:  (2, 2, 3)
dimension of the array: 3


In [37]:
# print 0th row of all the depth
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [38]:
# print 1st column of all the depth
print(arr3d[:,:,1:2])

[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]
